import { Col, Row } from 'antd';
import loginImage from '@/assets/login.png';
import Image from 'next/image';
import UserLoginForm from '@/components/ui/UserLoginForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Login | University Management',
  description: 'Generated by create next app',
};

const LoginPage = () => {
  return (
    <div>
      <Row justify="center" align="middle" style={{ minHeight: '100vh' }}>
        <Col sm={12} md={16} lg={10}>
          <Image src={loginImage} alt="login image" priority width={500} />
        </Col>
        <Col sm={12} md={8} lg={8}>
          <h1 style={{ marginBottom: '10px' }}>First login your account</h1>
          <div>
            <UserLoginForm />
          </div>
        </Col>
      </Row>
    </div>
  );
};

export default LoginPage;
